//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagsCloudVisualization.WFApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagsCloudVisualization.WFApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размеры изображения.
        /// </summary>
        internal static string ImageSettingsAction_Description {
            get {
                return ResourceManager.GetString("ImageSettingsAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение....
        /// </summary>
        internal static string ImageSettingsAction_Name {
            get {
                return ResourceManager.GetString("ImageSettingsAction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изображение в файл.
        /// </summary>
        internal static string SaveImageAction_Description {
            get {
                return ResourceManager.GetString("SaveImageAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить....
        /// </summary>
        internal static string SaveImageAction_Name {
            get {
                return ResourceManager.GetString("SaveImageAction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png.
        /// </summary>
        internal static string SaveImageAction_Perform_DefaultExt {
            get {
                return ResourceManager.GetString("SaveImageAction_Perform_DefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagCloud.png.
        /// </summary>
        internal static string SaveImageAction_Perform_FileName {
            get {
                return ResourceManager.GetString("SaveImageAction_Perform_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG (*.png)|*.png|JPG (*.jpg)|*.jpg|BMP (*.bmp)|*.bmp.
        /// </summary>
        internal static string SaveImageAction_Perform_Filter {
            get {
                return ResourceManager.GetString("SaveImageAction_Perform_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string SettingsForm_OnLoad_Text {
            get {
                return ResourceManager.GetString("SettingsForm_OnLoad_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить источник текста.
        /// </summary>
        internal static string SourceSettingsAction_Description {
            get {
                return ResourceManager.GetString("SourceSettingsAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Источник....
        /// </summary>
        internal static string SourceSettingsAction_Name {
            get {
                return ResourceManager.GetString("SourceSettingsAction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txt.
        /// </summary>
        internal static string SourceSettingsAction_Perform_DefaultExt {
            get {
                return ResourceManager.GetString("SourceSettingsAction_Perform_DefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстовый файл (*.txt)|*.txt|DOC (*.doc)|*.doc|DOCX (*.docx)|*.docx.
        /// </summary>
        internal static string SourceSettingsAction_Perform_Filter {
            get {
                return ResourceManager.GetString("SourceSettingsAction_Perform_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Облако тегов.
        /// </summary>
        internal static string TagsCloudAction_Name {
            get {
                return ResourceManager.GetString("TagsCloudAction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвета и шрифт для рисования тегов.
        /// </summary>
        internal static string TagsSettingsAction_Description {
            get {
                return ResourceManager.GetString("TagsSettingsAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Палитра и шрифт....
        /// </summary>
        internal static string TagsSettingsAction_Name {
            get {
                return ResourceManager.GetString("TagsSettingsAction_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Text_OK {
            get {
                return ResourceManager.GetString("Text_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags Cloud Visualizator....
        /// </summary>
        internal static string MainForm_OnShown_Name {
            get {
                return ResourceManager.GetString("MainForm_OnShown_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Call PictureBoxImageHolder.RecreateImage before other method call!
        /// </summary>
        internal static string PictureBoxImageHolder_ValidateImageCreation_Fail {
            get {
                return ResourceManager.GetString("PictureBoxImageHolder_ValidateImageCreation_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный тип файлов не поддерживается в качестве источника.
        /// </summary>
        internal static string TextReaderFactory_ResolveTextReader_Fail {
            get {
                return ResourceManager.GetString("TextReaderFactory_ResolveTextReader_Fail", resourceCulture);
            }
        }
    }
}
