//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagsCloudVisualization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagsCloudVisualization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры DeltaAngle и Distance не должны быть равны нулю. Пожалуйста, укажите корректные параметры..
        /// </summary>
        internal static string ArchimedeanSpiralSettings_ValidateArguments_Fail {
            get {
                return ResourceManager.GetString("ArchimedeanSpiralSettings_ValidateArguments_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина и высота прямоугольника должны быть больше нуля..
        /// </summary>
        internal static string BaseCloudLayouter_ValidateRectangleSize_Fail {
            get {
                return ResourceManager.GetString("BaseCloudLayouter_ValidateRectangleSize_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тело источника пусто. Пожалуйста, предоставьте другой файл..
        /// </summary>
        internal static string DocTextReader_GetBody_Fail {
            get {
                return ResourceManager.GetString("DocTextReader_GetBody_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ширина и высота изображения не могут быть меньше или равны нулю. Пожалуйста, введите корректные настройки..
        /// </summary>
        internal static string ImageSettings_ValidateWidthAndHeight_Fail {
            get {
                return ResourceManager.GetString("ImageSettings_ValidateWidthAndHeight_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файла источника по указанному пути не существует: {0}..
        /// </summary>
        internal static string SourceSettings_ValidatePathExists_Fail {
            get {
                return ResourceManager.GetString("SourceSettings_ValidatePathExists_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В качестве пути к файлу источника была предоставлена пустая строка. Пожалуйста, укажите верный путь к файлу..
        /// </summary>
        internal static string SourceSettings_ValidatePathNotNullOrEmpty_Fail {
            get {
                return ResourceManager.GetString("SourceSettings_ValidatePathNotNullOrEmpty_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный шрифт отстутствует в системе. Пожалуйста, введите корректное название шрифта..
        /// </summary>
        internal static string TagsSettings_ValidateFont_Fail {
            get {
                return ResourceManager.GetString("TagsSettings_ValidateFont_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер шрифта не может быть меньше или равен нулю. Пожалуйста, введите корректные настройки..
        /// </summary>
        internal static string TagsSettings_ValidateFontSize_Fail {
            get {
                return ResourceManager.GetString("TagsSettings_ValidateFontSize_Fail", resourceCulture);
            }
        }
    }
}
